FROM ubuntu:24.04

ARG VERSION
# Set TARGETARCH to the system architecture if not provided
ARG TARGETARCH
RUN if [ -z "$TARGETARCH" ]; then \
      arch=$(uname -m); \
      case "$arch" in \
        x86_64) TARGETARCH="amd64" ;; \
        aarch64) TARGETARCH="arm64" ;; \
        *) TARGETARCH="$arch" ;; \
      esac; \
      echo "Defaulting TARGETARCH to $TARGETARCH"; \
    else \
      echo "Using provided TARGETARCH: $TARGETARCH"; \
    fi

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt install -y socat wget curl xvfb libgtk-3-0 libnss3 libasound2t64 ca-certificates \
    # zlib1g-dev is required for arm64
    zlib1g-dev \
    --no-install-recommends && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN ARCH_SUFFIX=""; \
        if [ "$TARGETARCH" = "arm64" ]; then \
            ARCH_SUFFIX="-arm64"; \
        fi && \
    wget -O authoring-tool.AppImage \
    "https://packages.projekt-adler.eu/packages/authoring-tool/${VERSION}-linux${ARCH_SUFFIX}.AppImage" && \
    chmod +x authoring-tool.AppImage && \
    ./authoring-tool.AppImage --appimage-extract && \
    mv squashfs-root/* . && \
    rm -rf squashfs-root authoring-tool.AppImage

EXPOSE 8002

HEALTHCHECK --interval=5s --timeout=3s --start-period=60s --retries=3 CMD curl -f http://localhost:8001 || exit 1

CMD ["sh", "-c", "rm -f /tmp/.X*-lock && xvfb-run -e /dev/stdout ./authoring-tool --no-sandbox & socat TCP-LISTEN:8002,fork TCP:127.0.0.1:8001"]